apiData:
  url: https://graphigo.stg.dlive.tv/
  viewer1_loginEmail: 66@nqmo.com
  viewer1_pwd: password1234
  viewer1_username: dlive-degnujtptx
  viewer1_display: automation_viewer1
  follow_streamer: automation
  follow_displayName: automation
  follow_streamer_user: automation@nqmo.com
  follow_streamer_pwd: Pwd@1234
  follow_streamer_permlink: automation+2hatMquVg
  streamer_category_id: 18172     # qatest
  donate_value: 1
  send_message: for automation test   # send message and emo
  subscription_streamer: lauren         # 每次执行需要填写新的主播的名字，因为每次订阅过了就不能重新订阅了, 用username
  dashboard_info:
    search_tag: lol
    search_category: Art
  chest_info:
    chest_streamer: automation
    chest_streamer_permlimk: automation+2hatMquVg
    add_lemon: 5
    send_msg_chest_user1: Patrick1ios@nqmo.com
    send_msg_chest_user1_pwd: Pwd@1234
    msg: for automation test chest
    donate_chest_user2: Patrick2ios@nqmo.com
    chest_donate_user2_pwd: Pwd@1234
    donate_lemon_value: 1
    chest_user_no_point_user: Patrick3ios@nqmo.com
    chest_user_no_point_pwd: Pwd@1234
  gift_sub_info:
    streamer: automation
    give_sub_gift_user: 1193492940@qq.com
    give_sub_gift_user_pwd: password1234
    claim_user:
    -
      get_gift_sub_user: 37@nqmo.com
      get_gift_sub_user_pwd: password1234
    -
      get_gift_sub_user: 371@nqmo.com
      get_gift_sub_user_pwd: password1234
    -
      get_gift_sub_user: felix.li@tron.network
      get_gift_sub_user_pwd:  lfz123456
    -
      get_gift_sub_user: nick.ao@tron.network
      get_gift_sub_user_pwd: yang19881209@888
    -
      get_gift_sub_user: 39@nqmo.com
      get_gift_sub_user_pwd: password1234