apiData:
  url: https://graphigo.stg.dlive.tv/
  login_user: apple.zhang@dlive.tv
  pwd: password1234
  auth_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhaGExNiIsImRpc3BsYXluYW1lIjoiaGFoYTE2IiwiYXZhdGFyIjoiaHR0cHM6Ly9pbWFnZS5kbGl2ZWNkbi5jb20vYXZhdGFyL2RlZmF1bHQwLnBuZyIsInBhcnRuZXJfc3RhdHVzX3N0cmluZyI6Ik5PTkUiLCJpZCI6IiIsImxpZCI6MCwidHlwZSI6ImVtYWlsIiwicm9sZSI6Ik5vbmUiLCJvYXV0aF9hcHBpZCI6IiIsImV4cCI6MTY4NjgxODEyMSwiaWF0IjoxNjg0MTM5NzIxLCJpc3MiOiJETGl2ZSJ9.4DKq-wzvF_ULWMTgwLBd5yLWEVFMCegLkNrQW8E9U4o
  viewer1_username: 66@nqmo.com
  viewer1_pwd: password1234
  viewer1_auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRsaXZlLWRlZ251anRwdHgiLCJkaXNwbGF5bmFtZSI6ImF1dG9tYXRpb25fdmlld2VyMSIsImF2YXRhciI6Imh0dHBzOi8vaW1hZ2UuZGxpdmVjZG4uY29tL2F2YXRhci9kZWZhdWx0MjIucG5nIiwicGFydG5lcl9zdGF0dXNfc3RyaW5nIjoiTk9ORSIsImlkIjoiIiwibGlkIjowLCJ0eXBlIjoiZW1haWwiLCJyb2xlIjoiTm9uZSIsIm9hdXRoX2FwcGlkIjoiIiwiZXhwIjoxNjg4NjI3ODI0LCJpYXQiOjE2ODYwMzU4MjQsImlzcyI6IkRMaXZlIn0.VDDQcOgpiiH6pWLuvwLijhMPYzQv1RgZkSMCmYckVlI
  follow_streamer: automation
